#!/bin/bash
#SBATCH -A energybio-eng
#SBATCH -N 1
#SBATCH --partition=gpu
#SBATCH --cpus-per-task=1
#SBATCH --gpus=a100_1g.5gb:4
#SBATCH --job-name=r50g2
#SBATCH -t 60:00:00
#SBATCH --output="glp2.out"

#
##SBATCH --ntasks=1
##SBATCH --gres=gpu:a100:1

module load gcc/11.3.0   
module load openmpi/gcc/11.3.0/zen2/4.1.5   
module load cuda/gcc/11.3.0/zen2/12.3.0

export CUDA_VISIBLE_DEVICES=0

source ~/.bashrc.conda
conda activate Dock-MD-FEP

echo Time is `date`

# Generated by CHARMM-GUI (http://www.charmm-gui.org) v3.7
#
# This folder contains a pre-optimized PDB structure and OpenMM inputs.
# All input files were optimized for OpenMM v6.2 or above, so lower version of OpenMM can cause some errors.
# You can get the latest development version of OpenMM at the git repository:
# https://github.com/pandegroup/openmm

init="step3_input"
equi_prefix="step4_equilibration"
prod_prefix="step5_production"
prod_step="step5"

## Equilibration
input_param="-t toppar.str -p ${init}.psf -c ${init}.crd -b sysinfo.dat -ff CHARMM"
python -u openmm_run.py -i ${equi_prefix}.inp ${input_param} -orst ${equi_prefix}.rst -odcd ${equi_prefix}.dcd > ${equi_prefix}.out
#
# Production
# The OpenMM check point file (.rst) cannot be used in a different machine environment.
# So please make sure if you are using the same GPU and CUDA version of machine while doing additional
# production steps with the check point file.
cnt=79
cntmax=100

while [ ${cnt} -le ${cntmax} ]; do
    pcnt=$((${cnt}-1))
    istep=${prod_step}_${cnt}
    pstep=${prod_step}_${pcnt}
    if [ ${cnt} -eq 1 ]; then
      pstep=${equi_prefix}
    fi
    input_param="-t toppar.str -p ${init}.psf -c ${init}.crd -irst ${pstep}.rst"
    python -u openmm_run.py -i ${prod_prefix}.inp ${input_param} -orst ${istep}.rst -odcd ${istep}.dcd > ${istep}.out
    cnt=$((${cnt}+1))
done


